local stub = require("wow_stub")

local WATER = "|cnIQ1:|Hitem:159::::::::6:1485:::::::::|h[Refreshing Spring Water]|h|r"
local BREAD = "|cnIQ1:|Hitem:4540::::::::6:1485:::::::::|h[Tough Hunk of Bread]|h|r"

local function load()
    local LL = stub.LoadAddon()
    stub.FireEvent("PLAYER_LOGIN")
    return LL
end

T.test("RecordKill creates matching records in both scopes", function()
    local LL = load()
    local fired = 0
    LL.On("LEDGER_CHANGED", function() fired = fired + 1 end)
    stub.Advance(5)
    LL.Ledger.RecordKill(257532, "Windshaper Novice Seer")
    local all = LL.DB.mobs[257532]
    local ses = LL.Session.Get().mobs[257532]
    T.truthy(all); T.truthy(ses)
    T.eq(all.name, "Windshaper Novice Seer")
    T.eq(all.kills, 1); T.eq(ses.kills, 1)
    T.eq(all.coin, 0)
    T.deq(all.items, {}); T.deq(all.unclaimed, {})
    T.eq(all.lastUpdate, 1700000005)
    T.eq(fired, 1)
    LL.Ledger.RecordKill(257532, "Windshaper Novice Seer")
    T.eq(all.kills, 2); T.eq(ses.kills, 2)
    T.eq(LL.Ledger.Totals("session").kills, 2)
    T.eq(LL.Ledger.Totals("alltime").kills, 2)
end)

T.test("RecordKill without a name leaves it for later; SetName fills it in once", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, nil)
    T.isnil(LL.DB.mobs[257532].name)
    LL.Ledger.SetName(257532, "Seer")
    T.eq(LL.DB.mobs[257532].name, "Seer")
    T.eq(LL.Session.Get().mobs[257532].name, "Seer")
    LL.Ledger.SetName(257532, "Other")
    T.eq(LL.DB.mobs[257532].name, "Seer", "first name wins")
end)

T.test("RecordItem attributes to a mob and to the session totals", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.RecordItem(257532, "159:0", "Refreshing Spring Water", WATER, 2)
    LL.Ledger.RecordItem(257532, "159:0", "Refreshing Spring Water", WATER, 1)
    local all = LL.DB.mobs[257532].items["159:0"]
    T.eq(all.count, 3)
    T.eq(all.name, "Refreshing Spring Water")
    T.eq(all.link, WATER)
    T.eq(LL.Session.Get().mobs[257532].items["159:0"].count, 3)
    T.eq(LL.Ledger.Totals("session").itemCount, 3)
end)

T.test("RecordItem with no mob goes to the unattributed bucket", function()
    local LL = load()
    LL.Ledger.RecordItem(nil, "4540:0", "Tough Hunk of Bread", BREAD, 1)
    T.eq(LL.Session.Get().unattributed.items["4540:0"].count, 1)
    T.eq(LL.DB.unattributed.items["4540:0"].count, 1)
    T.eq(LL.Ledger.Totals("session").itemCount, 1)
    T.eq(LL.Ledger.Totals("session").kills, 0)
end)

T.test("RecordUnclaimed is kept apart from claimed items", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.RecordUnclaimed(257532, "4540:0", "Tough Hunk of Bread", BREAD, 1)
    T.eq(LL.DB.mobs[257532].unclaimed["4540:0"].count, 1)
    T.isnil(LL.DB.mobs[257532].items["4540:0"])
    T.eq(LL.Ledger.Totals("session").itemCount, 0)
    -- An unclaimed item with no mob is kept, dimmed, under Other loot.
    LL.Ledger.RecordUnclaimed(nil, "4540:0", "Tough Hunk of Bread", BREAD, 1)
    T.isnil(LL.DB.unattributed.items["4540:0"])
    T.eq(LL.DB.unattributed.unclaimed["4540:0"].count, 1)
    T.eq(LL.Session.Get().unattributed.unclaimed["4540:0"].count, 1)
    T.eq(LL.Ledger.Totals("session").itemCount, 0, "still not counted")
end)

T.test("RecordCoin adds to the mob and to the totals", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.RecordCoin(257532, 16)
    LL.Ledger.RecordCoin(257532, 7)
    LL.Ledger.RecordCoin(nil, 100)
    T.eq(LL.DB.mobs[257532].coin, 23)
    T.eq(LL.Session.Get().mobs[257532].coin, 23)
    T.eq(LL.DB.unattributed.coin, 100)
    T.eq(LL.Ledger.Totals("session").coin, 123)
    T.eq(LL.Ledger.Totals("alltime").coin, 123)
end)

T.test("loot for an unknown mob creates its record without a kill", function()
    local LL = load()
    LL.Ledger.RecordItem(251661, "4757:0", "Cracked Egg Shells", "link", 1)
    T.eq(LL.DB.mobs[251661].kills, 0)
    T.eq(LL.DB.mobs[251661].items["4757:0"].count, 1)
end)

T.test("ResetMob removes the mob from both scopes", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.RecordKill(251661, "Galestrider")
    LL.Ledger.RecordCoin(257532, 50)
    LL.Ledger.ResetMob(257532)
    T.isnil(LL.DB.mobs[257532])
    T.isnil(LL.Session.Get().mobs[257532])
    T.truthy(LL.DB.mobs[251661])
    T.eq(LL.Ledger.Totals("session").kills, 1)
    T.eq(LL.Ledger.Totals("session").coin, 0)
end)

T.test("ResetAll wipes records, session and history but keeps learned names and filters", function()
    local LL = load()
    LL.DB.npcNames[257532] = "Seer"
    LL.Ledger.Filter("6265:0", "Soul Shard", "link")
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.RecordCoin(nil, 5)
    LL.Session.Restart("old")
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.ResetAll()
    T.deq(LL.DB.mobs, {})
    T.eq(LL.DB.unattributed.coin, 0)
    T.deq(LL.Session.Get().mobs, {})
    T.eq(#LL.CharDB.history, 0)
    T.eq(LL.DB.npcNames[257532], "Seer")
    T.truthy(LL.Ledger.IsFiltered("6265:0"))
end)

T.test("filters block new records and are listed with their names", function()
    local LL = load()
    local fired = 0
    LL.On("FILTERS_CHANGED", function() fired = fired + 1 end)
    T.falsy(LL.Ledger.IsFiltered("6265:0"))
    LL.Ledger.Filter("6265:0", "Soul Shard", "shardlink")
    T.truthy(LL.Ledger.IsFiltered("6265:0"))
    T.eq(fired, 1)
    T.falsy(LL.Ledger.RecordItem(257532, "6265:0", "Soul Shard", "shardlink", 1))
    T.isnil(LL.DB.mobs[257532])
    T.falsy(LL.Ledger.RecordUnclaimed(257532, "6265:0", "Soul Shard", "shardlink", 1))
    local list = LL.Ledger.Filters()
    T.eq(#list, 1)
    T.eq(list[1].itemKey, "6265:0")
    T.eq(list[1].name, "Soul Shard")
    T.eq(list[1].link, "shardlink")
    LL.Ledger.Unfilter("6265:0")
    T.falsy(LL.Ledger.IsFiltered("6265:0"))
    T.eq(#LL.Ledger.Filters(), 0)
    T.eq(fired, 2)
end)

T.test("Mobs returns the right scope", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Session.Restart()
    T.truthy(LL.Ledger.Mobs("alltime")[257532])
    T.isnil(LL.Ledger.Mobs("session")[257532])
end)

T.test("ResetOther clears only the unattributed bucket", function()
    local LL = load()
    LL.Ledger.RecordKill(257532, "Seer")
    LL.Ledger.RecordCoin(nil, 40)
    LL.Ledger.RecordItem(nil, "4540:0", "Bread", BREAD, 1)
    LL.Ledger.ResetOther()
    T.eq(LL.DB.unattributed.coin, 0)
    T.deq(LL.DB.unattributed.items, {})
    T.eq(LL.Session.Get().unattributed.coin, 0)
    T.eq(LL.DB.mobs[257532].kills, 1)
end)
