local stub = require("wow_stub")

local WATER = "|cnIQ1:|Hitem:159::::::::6:1485:::::::::|h[Refreshing Spring Water]|h|r"
local EGG = "|cnIQ0:|Hitem:4757::::::::6:1485:::::::::|h[Cracked Egg Shells]|h|r"
local BOOTS = "|cnIQ2:|Hitem:6522:0:0:0:0:0:-12:1234567:6:1485:::::::::|h[Combat Boots of the Whale]|h|r"

T.test("ParseLink reads a bare modern link", function()
    local LL = stub.LoadAddon()
    local id, suffix, name, link = LL.Items.ParseLink(WATER)
    T.eq(id, 159)
    T.eq(suffix, 0)
    T.eq(name, "Refreshing Spring Water")
    T.eq(link, WATER)
end)

T.test("ParseLink finds the link inside chat text and leaves the count outside", function()
    local LL = stub.LoadAddon()
    local id, suffix, name, link = LL.Items.ParseLink("You receive loot: " .. EGG .. "x3.")
    T.eq(id, 4757)
    T.eq(suffix, 0)
    T.eq(name, "Cracked Egg Shells")
    T.eq(link, EGG)
end)

T.test("ParseLink keeps the random suffix from field 8", function()
    local LL = stub.LoadAddon()
    local id, suffix, name = LL.Items.ParseLink(BOOTS)
    T.eq(id, 6522)
    T.eq(suffix, -12)
    T.eq(name, "Combat Boots of the Whale")
end)

T.test("ParseLink handles links without a colour code and returns nil without a link", function()
    local LL = stub.LoadAddon()
    local id, suffix, name, link = LL.Items.ParseLink("|Hitem:2589::::::::6:1485:::::::::|h[Linen Cloth]|h")
    T.eq(id, 2589)
    T.eq(name, "Linen Cloth")
    T.eq(link, "|Hitem:2589::::::::6:1485:::::::::|h[Linen Cloth]|h")
    T.isnil(LL.Items.ParseLink("You loot 16 Copper"))
    T.isnil(LL.Items.ParseLink(nil))
end)

T.test("Key, SplitKey and ItemString round-trip", function()
    local LL = stub.LoadAddon()
    T.eq(LL.Items.Key(159, 0), "159:0")
    T.eq(LL.Items.Key(6522, -12), "6522:-12")
    T.eq(LL.Items.Key(159), "159:0")
    local id, suffix = LL.Items.SplitKey("6522:-12")
    T.eq(id, 6522)
    T.eq(suffix, -12)
    T.eq(LL.Items.ItemString("159:0"), "item:159:0:0:0:0:0:0")
    T.eq(LL.Items.ItemString("6522:-12"), "item:6522:0:0:0:0:0:-12")
end)

T.test("Icon is synchronous and accepts key, link or id", function()
    local LL = stub.LoadAddon()
    stub.SetItems({ [159] = { name = "Refreshing Spring Water", icon = 132794 } })
    T.eq(LL.Items.Icon("159:0"), 132794)
    T.eq(LL.Items.Icon(WATER), 132794)
    T.eq(LL.Items.Icon(159), 132794)
    T.isnil(LL.Items.Icon("999999:0"))
end)

T.test("Info requests a load once when uncached and resolves after the load event", function()
    local LL = stub.LoadAddon()
    stub.SetItems({ [159] = { name = "Refreshing Spring Water", icon = 132794, quality = 1, sellPrice = 13, loaded = false } })
    T.isnil(LL.Items.Info(WATER))
    T.isnil(LL.Items.Info(WATER))
    T.eq(stub.itemLoadRequests[159], 1, "one load request")
    stub.LoadItem(159)
    local info = LL.Items.Info(WATER)
    T.truthy(info)
    T.eq(info.name, "Refreshing Spring Water")
    T.eq(info.quality, 1)
    T.eq(info.sellPrice, 13)
    T.eq(info.icon, 132794)
end)

T.test("Info caches until Flush", function()
    local LL = stub.LoadAddon()
    stub.SetItems({ [159] = { name = "Water", sellPrice = 13 } })
    T.eq(LL.Items.Info(WATER).sellPrice, 13)
    stub.items[159].sellPrice = 99
    T.eq(LL.Items.Info(WATER).sellPrice, 13, "cached")
    LL.Items.Flush()
    T.eq(LL.Items.Info(WATER).sellPrice, 99, "after flush")
end)

T.test("Info accepts a key and builds the item string", function()
    local LL = stub.LoadAddon()
    stub.SetItems({ [2589] = { name = "Linen Cloth", sellPrice = 13 } })
    T.eq(LL.Items.Info("2589:0").name, "Linen Cloth")
end)
